<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6b991b6ec31298354dcd47894735eb21
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/App',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6b991b6ec31298354dcd47894735eb21::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6b991b6ec31298354dcd47894735eb21::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
